MODEL:
  TYPE: aff 
  NAME: aff_base_22kto1k_384 
  DROP_PATH_RATE: 0.2
  AFF:
    DEPTHS: [3,4,18,2]
    NUM_HEADS: [4,8,16,32]
    MLP_RATIO: 3.
    EMBED_DIM: [128, 256, 512, 1024]
    CLUSTER_SIZE: 24
    NBHD_SIZE: [144,144,144,144]
    LAYER_SCALE: 1e-5 # turned off if 0.0
    ALPHA: 4.0
    DS_RATE: 0.25
  PRETRAINED: aff_base_22k.pth
DATA:
  DATASET: imagenet 
  IMG_SIZE: 384 
  BATCH_SIZE: 16
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  MIN_LR: 2e-07
  USE_EMA: False 
  EMA_DECAY: 0.9998
  WARMUP_LR: 2e-08
  ACCUMULATION_STEPS: 4
AUG:
  MIXUP: 0.8
  CUTMIX: 1.0
TEST:
  CROP: False
