MODEL:
  TYPE: aff 
  NAME: aff_tiny_1_4th
  DROP_PATH_RATE: 0.2
  AFF:
    DEPTHS: [3,4,18,5]
    NUM_HEADS: [2,4,8,16]
    MLP_RATIO: 3.
    EMBED_DIM: [64,128,256,512]
    CLUSTER_SIZE: 8
    NBHD_SIZE: [48,48,48,49]
    ALPHA: 4.0
    DS_RATE: 0.25
DATA:
  DATASET: imagenet 
  IMG_SIZE: 224
  BATCH_SIZE: 256
TRAIN:
  EPOCHS: 300
  BASE_LR: 5e-4
  MIN_LR: 5e-6
  WARMUP_LR: 5e-7
AUG:
  MIXUP: 0.8
  CUTMIX: 1.0
